services:
  - type: web
    name: sg2-dashboard-preview
    runtime: node
    plan: starter
    autoDeploy: true
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false